controller_manager:
  ros__parameters:
    update_rate: 100 

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["wheel_back_left_joint"]
    right_wheel_names: ["wheel_back_right_joint"]

    wheel_separation: 0.5
    wheel_radius: 0.15

    cmd_vel_timeout: 0.5
    enable_odom_tf: true
    odom_frame_id: "odom"
    base_frame_id: "base_link"

    publish_rate: 50.0

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.5
        min_velocity: -0.5
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.0
        min_velocity: -1.0

